from .base import *  # noqa: F401,F403
from .base import _env, _env_list

DEBUG = False
ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS")
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_DOMAIN = _env("SESSION_COOKIE_DOMAIN") or None
CSRF_COOKIE_DOMAIN = _env("CSRF_COOKIE_DOMAIN") or None
CSRF_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
