import json
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand

from submissions.registry import PILLARS, public_schema, section_count_fields


class Command(BaseCommand):
    help = "Regenerate knowledge/03-forms-catalog.md and knowledge/data/form_registry.json from the registry."

    def add_arguments(self, parser):
        parser.add_argument("--out", default=str(Path(settings.BASE_DIR).parent / "knowledge"))

    def handle(self, *args, **opts):
        out = Path(opts["out"])
        (out / "data").mkdir(parents=True, exist_ok=True)
        (out / "data" / "form_registry.json").write_text(json.dumps(public_schema(), indent=1, ensure_ascii=False),
                                                         encoding="utf-8")
        lines = ["# 03 · Forms catalog (all pillars, counts and sub-forms)\n",
                 "Generated by `python manage.py export_registry` from `backend/submissions/registry.py`. "
                 "Column **legacy** = field name in the old portal / its API. `*` = required.\n"]
        nf = 0
        for p in PILLARS:
            lines.append(f"\n## Pillar {p['key']} — {p['name']} (legacy `{p['legacy_form']}`)\n\n_{p['tagline']}_\n")
            lines.append("### Header form: counts\n\n| field | label | type | legacy |\n|---|---|---|---|")
            lines += [f"| `{f['name']}` | {f['label']} | {f['type']} | `{f['legacy']}` |" for f in p["counts"]]
            for s in p["sections"]:
                lines.append(f"\n### {s['key']} · {s['title']}\n\nTemplate #{s['template']} · code {s['code']} · "
                             f"count `{', '.join(section_count_fields(s))}` · legacy POST `{s['legacy_endpoint']}`\n")
                lines.append("| field | label | type | options | legacy |\n|---|---|---|---|---|")
                for f in s["fields"]:
                    nf += 1
                    opts_ = ", ".join(f["options"]) if isinstance(f.get("options"), list) else (
                        "28 departments" if f["type"] == "department" else "")
                    if f.get("other"):
                        opts_ += " (+ free-text Other)"
                    help_ = f" — _{f['help']}_" if f.get("help") else ""
                    lines.append(f"| `{f['name']}`{'*' if f['required'] else ''} | {f['label']}{help_} | {f['type']} "
                                 f"| {opts_} | `{f['legacy']}` |")
        lines.insert(2, f"\n**Totals:** 3 pillars · {sum(len(p['sections']) for p in PILLARS)} sub-forms · "
                        f"{nf} sub-form fields · {sum(len(p['counts']) for p in PILLARS)} count fields.\n")
        (out / "03-forms-catalog.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"Wrote {out / '03-forms-catalog.md'}"))
