# Generated by Django 4.2.30 on 2026-10-05 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import submissions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(choices=[('RE', 'Research Excellence'), ('IC', 'Innovation & Commercialization'), ('SCB', 'Sustainability & Capacity Building')], max_length=3)),
                ('faculty_name', models.CharField(max_length=150)),
                ('faculty_email', models.EmailField(max_length=254)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('returned', 'Returned for revision'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=15)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='org.reportingcycle')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='org.department')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('A1', 'A1 · Research projects submitted for funding to HEC'), ('A2', 'A2 · Research projects submitted for funding to non-HEC sources (national or international)'), ('A3', 'A3 · Research projects approved for funding by HEC'), ('A4', 'A4 · Research projects approved for funding by non-HEC sources'), ('A5', 'A5 · HEC-funded research projects completed'), ('A6', 'A6 · Non-HEC-funded research projects completed'), ('A7', 'A7 · Joint research projects submitted (national / international funding agencies)'), ('A8', 'A8 · Joint research projects approved (national / international funding agencies)'), ('A9', 'A9 · Joint research projects completed (national / international funding agencies)'), ('A10', 'A10 · Contract research awarded'), ('A11', 'A11 · Policy advocacy / case studies'), ('A12', 'A12 · Research links established (academic / research linkages)'), ('A13', 'A13 · Civic engagement events / initiatives'), ('A14', 'A14 · Consultancy contracts executed through ORIC'), ('A15', 'A15 · Liaison developed with Advanced Studies & Research Board (AS&RB)'), ('B1', 'B1 · IP disclosures made with patent department / patent attorney'), ('B2', 'B2 · Patents / trademarks / design patents / copyrights filed or granted'), ('B3', 'B3 · IP licensing negotiations initiated'), ('B4', 'B4 · Exclusive or non-exclusive licenses signed'), ('B5', 'B5 · Products / prototypes developed'), ('B6', 'B6 · Science / arts / design products displayed'), ('B7', 'B7 · Visits by representatives of industry or community'), ('B8', 'B8 · Agreements signed for collaboration with industry, government or community'), ('B9', 'B9 · National or international honors / awards won'), ('B10', 'B10 · Trainings / workshops / seminars / conferences arranged by ORIC'), ('B11', 'B11 · Trainings / workshops / seminars / conferences by other HEIs or organizations (attended)'), ('B12', 'B12 · Exhibitions / showcasing events / industry linkage fairs / IP stimulus arranged by ORIC'), ('B13', 'B13 · Research publications'), ('C1', 'C1 · Faculty-led startups'), ('C2', 'C2 · Faculty startups as spin-offs'), ('C3', 'C3 · Funding secured by startups / spin-offs'), ('C4', 'C4 · Entrepreneurship events / activities')], max_length=4)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='submissions.submission')),
            ],
            options={
                'ordering': ['section', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', 'Submitted'), ('start_review', 'Review started'), ('return', 'Returned for revision'), ('approve', 'Approved'), ('reject', 'Rejected'), ('reopen', 'Reopened'), ('comment', 'Comment')], max_length=15)),
                ('from_status', models.CharField(blank=True, max_length=15)),
                ('to_status', models.CharField(blank=True, max_length=15)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='submissions.submission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=60)),
                ('file', models.FileField(upload_to=submissions.models.evidence_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='submissions.sectionentry')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['field', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['pillar', 'status'], name='submissions_pillar_ac02f5_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['department', 'cycle'], name='submissions_departm_0a7d4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('pillar', 'cycle', 'owner'), name='one_submission_per_pillar_cycle_owner'),
        ),
        migrations.AddIndex(
            model_name='sectionentry',
            index=models.Index(fields=['section'], name='submissions_section_234932_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidencefile',
            constraint=models.UniqueConstraint(fields=('entry', 'field'), name='one_file_per_entry_field'),
        ),
    ]
