# Generated by Django 4.2.30 on 2026-10-05 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccountStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('social_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='socialaccount.socialaccount')),
            ],
            options={
                'verbose_name': 'social account status',
                'verbose_name_plural': 'social account statuses',
            },
        ),
    ]
